<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">javaService_ToSleep</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNCmludCBp
VGltZSA9IEludGVnZXIucGFyc2VJbnQoSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJz
b3IsICJJbnB1dFN0cmluZyIgKSk7DQovL2ludCBpVGltZSA9IDgwMDAwOw0KU3RyaW5nCXNPdXRw
dXRNZXNzYWdlID0gIkRlbGF5U2VydmljZSBjYWxsIHdpdGggdGltZTogIiArIEludGVnZXIudG9T
dHJpbmcoaVRpbWUpICsgIiBtaWxpc2Vjb25kcyI7DQpwaXBlbGluZUN1cnNvci5kZXN0cm95KCk7
DQoNCnRyeSB7DQoJVGhyZWFkLnNsZWVwKGlUaW1lKTsNCn0gY2F0Y2ggKEludGVycnVwdGVkRXhj
ZXB0aW9uIGUpIHsNCgkvLyBUT0RPIEF1dG8tZ2VuZXJhdGVkIGNhdGNoIGJsb2NrDQoJZS5wcmlu
dFN0YWNrVHJhY2UoKTsNCn0NCg0KLy8gcGlwZWxpbmUgZm9yIGNyZWF0aW5nIG91dHB1dA0KSURh
dGFDdXJzb3IgcGlwZWxpbmVDdXJzb3JfMSA9IHBpcGVsaW5lLmdldEN1cnNvcigpOw0KSURhdGFV
dGlsLnB1dCggcGlwZWxpbmVDdXJzb3JfMSwgIk91dHB1dFN0cmluZyIsIHNPdXRwdXRNZXNzYWdl
ICk7DQpwaXBlbGluZUN1cnNvcl8xLmRlc3Ryb3koKTs=</value>
</Values>
